#!/bin/bash
# Display commit message format information

echo ""
echo "📝 Commit Message Format:"
echo ""
echo "  <type>(<scope>): <subject>"
echo ""
echo "  Example: feat(architect): add draft creation service"
echo ""
echo "⚠️  REQUIRED:"
echo "  • type: feat, fix, docs, style, refactor, perf, test, chore, ci, build, revert"
echo "  • scope: module name in kebab-case (REQUIRED)"
echo "  • subject: lowercase, max 72 chars, no period at end"
echo ""
echo "📌 Scopes:"
echo "  Backend: architect, workflow, code-review, documentation, github, ai-provider,"
echo "           database, queue, api, common"
echo "  Frontend: kanban, draft-viewer, conversation-form, ui, lib"
echo "  Shared: shared, types, deps, config"
echo ""
echo "✅ Valid examples:"
echo "  • feat(architect): add draft creation service"
echo "  • fix(kanban): resolve drag and drop issue"
echo "  • docs(readme): update installation steps"
echo "  • chore(deps): update prettier to 3.8.1"
echo ""
echo "❌ Invalid examples:"
echo "  • feat: add feature (missing scope)"
echo "  • feat(Architect): add feature (scope not kebab-case)"
echo "  • feat(architect): Add feature (subject not lowercase)"
echo "  • feat(architect): add feature. (period at end)"
echo ""
