#!/usr/bin/env bash
# commit-format-info.sh — display commit message format information.

echo ""
echo "📝 Commit Message Format:"
echo ""
echo "  <type>(<scope>): <subject>"
echo ""
echo "  Example: feat(auth): add JWT token refresh"
echo ""
echo "⚠️  REQUIRED:"
echo "  • type:    feat, fix, docs, style, refactor, perf, test, chore, ci, build, revert"
echo "  • scope:   module name in kebab-case (REQUIRED — see commitlint.config.mjs)"
echo "  • subject: lowercase, imperative mood, max 72 chars, no period at end"
echo ""
echo "✅ Valid examples:"
echo "  • feat(auth): add JWT token refresh"
echo "  • fix(api): handle empty response from payment gateway"
echo "  • docs(readme): update installation steps"
echo "  • chore(deps): update prettier to 3.8.1"
echo ""
echo "❌ Invalid examples:"
echo "  • feat: add feature             (missing scope)"
echo "  • feat(Auth): add feature       (scope not kebab-case)"
echo "  • feat(auth): Add feature       (subject not lowercase)"
echo "  • feat(auth): add feature.      (period at end)"
echo ""
echo "📌 Branch format:"
echo "  <type>/<issue-number>-<short-description>"
echo "  Example: feature/0001-user-authentication"
echo ""
