name: Lint & Format

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Markdownlint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up pnpm
              uses: pnpm/action-setup@v6
              with:
                  version: '10'
                  run_install: false

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '24'
                  cache: 'pnpm'

            - name: Install global tools
              run: npm install -g markdownlint-cli2

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint markdown
              run: pnpm run lint:check

    format:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up pnpm
              uses: pnpm/action-setup@v6
              with:
                  version: '10'
                  run_install: false

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '24'
                  cache: 'pnpm'

            - name: Install global tools
              run: npm install -g prettier

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check formatting
              run: pnpm run format:check
